version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - "curl -s -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq"
      - "chmod +x /usr/bin/jq"
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - cd ..
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - cd terraform
      - terraform init
      - terraform apply -auto-approve -no-color
  post_build:
    commands:
      - echo Build completed on `date`
