version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - cd "$CODEBUILD_SRC_DIR" 
  build:
    commands:
      - echo Build started on `date` and build "$CODEBUILD_BUILD_NUMBER"
      - cd terraform
      - terraform init
      - TF_VAR_tag=1.0."$CODEBUILD_BUILD_NUMBER" terraform apply -auto-approve -no-color
  post_build:
    commands:
      - echo Build completed on `date`
